// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/bearchit/gox/entx/internal/document/ent/revision"
	"github.com/bearchit/gox/timex"
)

// Revision is the model entity for the Revision schema.
type Revision struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// LifespanStartAt holds the value of the "lifespan_start_at" field.
	LifespanStartAt time.Time `json:"lifespan_start_at,omitempty"`
	// LifespanEndAt holds the value of the "lifespan_end_at" field.
	LifespanEndAt time.Time `json:"lifespan_end_at,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Revision) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case revision.FieldID:
			values[i] = new(sql.NullInt64)
		case revision.FieldLifespanStartAt, revision.FieldLifespanEndAt:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Revision", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Revision fields.
func (r *Revision) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case revision.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			r.ID = int(value.Int64)
		case revision.FieldLifespanStartAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field lifespan_start_at", values[i])
			} else if value.Valid {
				r.LifespanStartAt = value.Time
			}
		case revision.FieldLifespanEndAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field lifespan_end_at", values[i])
			} else if value.Valid {
				r.LifespanEndAt = value.Time
			}
		}
	}
	return nil
}

// Update returns a builder for updating this Revision.
// Note that you need to call Revision.Unwrap() before calling this method if this Revision
// was returned from a transaction, and the transaction was committed or rolled back.
func (r *Revision) Update() *RevisionUpdateOne {
	return (&RevisionClient{config: r.config}).UpdateOne(r)
}

// Unwrap unwraps the Revision entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (r *Revision) Unwrap() *Revision {
	tx, ok := r.config.driver.(*txDriver)
	if !ok {
		panic("ent: Revision is not a transactional entity")
	}
	r.config.driver = tx.drv
	return r
}

// String implements the fmt.Stringer.
func (r *Revision) String() string {
	var builder strings.Builder
	builder.WriteString("Revision(")
	builder.WriteString(fmt.Sprintf("id=%v", r.ID))
	builder.WriteString(", lifespan_start_at=")
	builder.WriteString(r.LifespanStartAt.Format(time.ANSIC))
	builder.WriteString(", lifespan_end_at=")
	builder.WriteString(r.LifespanEndAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

func (r *Revision) Lifespan() (*timex.TimeRange, error) {
	return timex.NewTimeRange(r.LifespanStartAt, r.LifespanEndAt)
}

// Revisions is a parsable slice of Revision.
type Revisions []*Revision

func (r Revisions) config(cfg config) {
	for _i := range r {
		r[_i].config = cfg
	}
}
