// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Collection is the predicate function for collection builders.
type Collection func(*sql.Selector)

// Document is the predicate function for document builders.
type Document func(*sql.Selector)

// Revision is the predicate function for revision builders.
type Revision func(*sql.Selector)
