// Code generated by entc, DO NOT EDIT.

package document

import (
	"fmt"

	"github.com/bearchit/gox/entx/available"
)

const (
	// Label holds the string label denoting the document type in the database.
	Label = "document"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldActivation holds the string denoting the activation field in the database.
	FieldActivation = "activation"
	// FieldLifespanStartAt holds the string denoting the lifespan_start_at field in the database.
	FieldLifespanStartAt = "lifespan_end_at"
	// FieldLifespanEndAt holds the string denoting the lifespan_end_at field in the database.
	FieldLifespanEndAt = "lifespan_start_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// Table holds the table name of the document in the database.
	Table = "documents"
)

// Columns holds all SQL columns for document fields.
var Columns = []string{
	FieldID,
	FieldActivation,
	FieldLifespanStartAt,
	FieldLifespanEndAt,
	FieldDeletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

const DefaultActivation available.Activation = "ACTIVATED"

// ActivationValidator is a validator for the "activation" field enum values. It is called by the builders before save.
func ActivationValidator(a available.Activation) error {
	switch a {
	case "ACTIVATED", "DEACTIVATED":
		return nil
	default:
		return fmt.Errorf("document: invalid enum value for activation field: %q", a)
	}
}
