// Code generated by entc, DO NOT EDIT.

package document

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/bearchit/gox/entx/available"
	"github.com/bearchit/gox/entx/internal/document/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// LifespanStartAt applies equality check predicate on the "lifespan_start_at" field. It's identical to LifespanStartAtEQ.
func LifespanStartAt(v time.Time) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLifespanStartAt), v))
	})
}

// LifespanEndAt applies equality check predicate on the "lifespan_end_at" field. It's identical to LifespanEndAtEQ.
func LifespanEndAt(v time.Time) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLifespanEndAt), v))
	})
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDeletedAt), v))
	})
}

// ActivationEQ applies the EQ predicate on the "activation" field.
func ActivationEQ(v available.Activation) predicate.Document {
	vc := v
	return predicate.Document(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldActivation), vc))
	})
}

// ActivationNEQ applies the NEQ predicate on the "activation" field.
func ActivationNEQ(v available.Activation) predicate.Document {
	vc := v
	return predicate.Document(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldActivation), vc))
	})
}

// ActivationIn applies the In predicate on the "activation" field.
func ActivationIn(vs ...available.Activation) predicate.Document {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Document(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldActivation), v...))
	})
}

// ActivationNotIn applies the NotIn predicate on the "activation" field.
func ActivationNotIn(vs ...available.Activation) predicate.Document {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Document(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldActivation), v...))
	})
}

// LifespanStartAtEQ applies the EQ predicate on the "lifespan_start_at" field.
func LifespanStartAtEQ(v time.Time) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLifespanStartAt), v))
	})
}

// LifespanStartAtNEQ applies the NEQ predicate on the "lifespan_start_at" field.
func LifespanStartAtNEQ(v time.Time) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldLifespanStartAt), v))
	})
}

// LifespanStartAtIn applies the In predicate on the "lifespan_start_at" field.
func LifespanStartAtIn(vs ...time.Time) predicate.Document {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Document(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldLifespanStartAt), v...))
	})
}

// LifespanStartAtNotIn applies the NotIn predicate on the "lifespan_start_at" field.
func LifespanStartAtNotIn(vs ...time.Time) predicate.Document {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Document(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldLifespanStartAt), v...))
	})
}

// LifespanStartAtGT applies the GT predicate on the "lifespan_start_at" field.
func LifespanStartAtGT(v time.Time) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldLifespanStartAt), v))
	})
}

// LifespanStartAtGTE applies the GTE predicate on the "lifespan_start_at" field.
func LifespanStartAtGTE(v time.Time) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldLifespanStartAt), v))
	})
}

// LifespanStartAtLT applies the LT predicate on the "lifespan_start_at" field.
func LifespanStartAtLT(v time.Time) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldLifespanStartAt), v))
	})
}

// LifespanStartAtLTE applies the LTE predicate on the "lifespan_start_at" field.
func LifespanStartAtLTE(v time.Time) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldLifespanStartAt), v))
	})
}

// LifespanStartAtIsNil applies the IsNil predicate on the "lifespan_start_at" field.
func LifespanStartAtIsNil() predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldLifespanStartAt)))
	})
}

// LifespanStartAtNotNil applies the NotNil predicate on the "lifespan_start_at" field.
func LifespanStartAtNotNil() predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldLifespanStartAt)))
	})
}

// LifespanEndAtEQ applies the EQ predicate on the "lifespan_end_at" field.
func LifespanEndAtEQ(v time.Time) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLifespanEndAt), v))
	})
}

// LifespanEndAtNEQ applies the NEQ predicate on the "lifespan_end_at" field.
func LifespanEndAtNEQ(v time.Time) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldLifespanEndAt), v))
	})
}

// LifespanEndAtIn applies the In predicate on the "lifespan_end_at" field.
func LifespanEndAtIn(vs ...time.Time) predicate.Document {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Document(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldLifespanEndAt), v...))
	})
}

// LifespanEndAtNotIn applies the NotIn predicate on the "lifespan_end_at" field.
func LifespanEndAtNotIn(vs ...time.Time) predicate.Document {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Document(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldLifespanEndAt), v...))
	})
}

// LifespanEndAtGT applies the GT predicate on the "lifespan_end_at" field.
func LifespanEndAtGT(v time.Time) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldLifespanEndAt), v))
	})
}

// LifespanEndAtGTE applies the GTE predicate on the "lifespan_end_at" field.
func LifespanEndAtGTE(v time.Time) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldLifespanEndAt), v))
	})
}

// LifespanEndAtLT applies the LT predicate on the "lifespan_end_at" field.
func LifespanEndAtLT(v time.Time) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldLifespanEndAt), v))
	})
}

// LifespanEndAtLTE applies the LTE predicate on the "lifespan_end_at" field.
func LifespanEndAtLTE(v time.Time) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldLifespanEndAt), v))
	})
}

// LifespanEndAtIsNil applies the IsNil predicate on the "lifespan_end_at" field.
func LifespanEndAtIsNil() predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldLifespanEndAt)))
	})
}

// LifespanEndAtNotNil applies the NotNil predicate on the "lifespan_end_at" field.
func LifespanEndAtNotNil() predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldLifespanEndAt)))
	})
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Document {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Document(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldDeletedAt), v...))
	})
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Document {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.Document(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldDeletedAt), v...))
	})
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldDeletedAt)))
	})
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldDeletedAt)))
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Document) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Document) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Document) predicate.Document {
	return predicate.Document(func(s *sql.Selector) {
		p(s.Not())
	})
}
